"""Every user-facing string generated by this project, checked for false certainty.

A research page can mislead without a single wrong number, by writing "will" where
it means "might" and "guaranteed" where it means "historically usually". These
tests walk every generated JSON blob and fail on the vocabulary of certainty and
on price predictions stated as fact.

The lists are deliberately blunt. A false positive here costs one rephrasing; a
false negative ships a sentence that promises something nobody can deliver.
"""
import json
import re
from pathlib import Path

import pytest

from an import analysis, positioning

ROOT = Path(__file__).resolve().parent.parent

# Phrases that assert an outcome. Matched case-insensitively on word boundaries.
FORBIDDEN = [
    r"\bguarantee\w*\b",
    r"\brisk[- ]free\b",
    r"\bsure thing\b",
    r"\bcan'?t lose\b",
    r"\bcannot lose\b",
    r"\bno[- ]brainer\b",
    r"\bwill (?:rise|fall|go up|go down|outperform|underperform|beat|double|reach|hit)\b",
    r"\bis going to (?:rise|fall|beat|double)\b",
    r"\bcertain to\b",
    r"\bdefinitely will\b",
    r"\bassured\b",
    r"\bwe (?:know|are certain) (?:it|this) will\b",
    r"\bshould buy\b",
    r"\bmust buy\b",
    r"\bstrong buy\b",
    r"\bprice target of\b",
]

# Words that promise without hedging. Allowed only in a phrase that already hedges.
HEDGE_NEARBY = re.compile(
    r"\b(may|might|could|if|would|unless|whether|risk|uncertain|not|cannot|no |never|"
    r"appears|suggest\w*|estimate\w*|expect\w*|guidance|guided|assum\w*)\b", re.I)


def walk_strings(obj, path="$"):
    if isinstance(obj, str):
        yield path, obj
    elif isinstance(obj, dict):
        for k, v in obj.items():
            yield from walk_strings(v, f"{path}.{k}")
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            yield from walk_strings(v, f"{path}[{i}]")


# A negation immediately before a forbidden phrase inverts it. "not that it will go
# up" is exactly the sentence this project should be writing, and a guard that
# fails it would push the text towards saying less rather than more.
NEGATED = re.compile(r"(?:\bnot\b|\bnever\b|\bno\b|\bnothing\b|\bnone\b|\bneither\b|"
                     r"\bcannot\b|\bwithout\b)[^.;]{0,40}$", re.I)


def check(obj, label):
    bad = []
    for path, s in walk_strings(obj):
        for pat in FORBIDDEN:
            for m in re.finditer(pat, s, re.I):
                before = s[max(0, m.start() - 60): m.start()]
                if NEGATED.search(before):
                    continue
                bad.append(f"{label} {path}: {m.group(0)!r} in {s[:140]!r}")
    return bad


def test_the_guard_catches_what_it_is_meant_to():
    """A guard nobody tested is a guard that passes everything."""
    assert check({"a": "This is a guaranteed winner"}, "t")
    assert check({"a": "It will double by year end"}, "t")
    assert check({"a": "risk-free carry"}, "t")
    assert check({"a": "price target of $300"}, "t")
    assert not check({"a": "It might double if bookings hold"}, "t")
    assert not check({"a": "What would prove this wrong is a close under $150."}, "t")
    # Negated forms are the sentences this project should be writing.
    assert not check({"a": "A higher score does not mean the name will go up."}, "t")
    assert not check({"a": "Nothing here is guaranteed."}, "t")
    # ...but the negation has to be near enough to actually apply.
    assert check({"a": "This is not a recommendation. Buying now will double your money."}, "t")


def test_positioning_memo_is_clean():
    bad = check(positioning.build_memo(built_at="X"), "memo")
    assert not bad, "\n".join(bad)


def test_every_analysis_record_is_clean():
    bad = []
    for t, r in analysis.build_all(built_at="X").items():
        bad += check(r, t)
    assert not bad, "\n".join(bad[:20])


@pytest.mark.parametrize("name", ["positioning.json", "backtest.json", "scorecard.json", "tracker.json", "watch.json"])
def test_built_json_is_clean(name):
    p = ROOT / "dashboard" / name
    if not p.exists():
        pytest.skip(f"{name} not built")
    bad = check(json.loads(p.read_text()), name)
    assert not bad, "\n".join(bad[:20])


def test_no_bare_future_tense_about_prices_in_generated_prose():
    """"The stock will" is the shape of the sentence this project must never write."""
    memo = positioning.build_memo(built_at="X")
    for path, s in walk_strings(memo):
        for m in re.finditer(r"\b(?:the )?(?:stock|share price|price|it) will\b", s, re.I):
            window = s[max(0, m.start() - 90): m.end() + 90]
            assert HEDGE_NEARBY.search(window), f"{path}: unhedged prediction in {window!r}"


def test_the_disclaimer_is_present_everywhere_it_should_be():
    memo = positioning.build_memo(built_at="X")
    assert "not personalised financial advice" in memo["disclaimer"]
    for t, r in analysis.build_all(built_at="X").items():
        assert "not personalised financial advice" in r["disclaimer"], t


def test_confidence_is_stated_on_every_candidate():
    memo = positioning.build_memo(built_at="X")
    for c in memo["candidates"]:
        assert c["confidence"]
        assert any(w in c["confidence"].lower() for w in ("moderate", "low", "bounded", "no filing"))


def test_backtest_never_claims_proof():
    p = ROOT / "dashboard" / "backtest.json"
    if not p.exists():
        pytest.skip("not built")
    blob = p.read_text().lower()
    for phrase in ("is proven", "has been proven", "proves that", "guaranteed",
                   "reliable edge", "consistently beats", "definitive evidence"):
        assert phrase not in blob, phrase
    # The one legitimate use of the word is the look-ahead flag, which says to treat
    # an implausible result as a bug until proven otherwise.
    assert "until proven otherwise" in blob


_SENTENCE_START_NUMERAL = re.compile(r"(?:^|(?<=[.!?]) )(\d[\d,.]*[-\s])")

# Only fields this project writes as prose. `detail` and `text` are value cells
# that sit beside a label ("estimate revisions, 30 days" / "8 raised next-year
# estimates, 19 cut them"), and quoted fields carry a source's own words, which
# must not be rewritten to suit a house style.
_PROSE_KEYS = ("caveat", "basis_warning", "reasoning", "gaps", "why", "note",
               "limitations", "caveats", "basis_note", "price_trigger_note")


def _prose_strings(obj):
    for path, s in walk_strings(obj):
        key = path.rsplit(".", 1)[-1].split("[")[0]
        if key in _PROSE_KEYS or any(f".{k}[" in path or f".{k}." in path for k in _PROSE_KEYS):
            yield path, s


def test_no_generated_prose_sentence_opens_with_a_numeral():
    """A style rule, but one this project broke twice in a day.

    Both were the same shape: a count interpolated into a sentence that happened
    to start with it, giving "2 numbers have a midpoint" and "A 4-point median is
    a thin basis". A numeral set in the monospace face at the head of a sentence
    reads as a list item rather than prose, and the fix is always to spell the
    word or reorder the clause.

    Scoped to the fields written as prose. The value cells beside a label are
    legitimately numeric and quoted text belongs to whoever wrote it.
    """
    bad = []
    for label, obj in (
        ("positioning.json", json.loads((ROOT / "dashboard" / "positioning.json").read_text())),
        ("analysis records", analysis.build_all(built_at="X")),
    ):
        for path, s in _prose_strings(obj):
            if len(s) < 40 or "\n" in s:
                continue
            m = _SENTENCE_START_NUMERAL.search(s)
            if m:
                bad.append(f"{label} {path}: sentence opens {m.group(1)!r} in {s[:120]!r}")
    assert not bad, "\n".join(bad[:20])


def test_that_numeral_guard_catches_what_it_is_meant_to():
    hit = _SENTENCE_START_NUMERAL.search(
        "Only 2 fiscal year ends carry both. 2 numbers have a midpoint but not a median at all.")
    assert hit and hit.group(1).startswith("2 ")
    assert not _SENTENCE_START_NUMERAL.search(
        "Only 2 fiscal year ends carry both. Two numbers have a midpoint but not a median at all.")


def test_the_prose_scope_is_not_empty():
    """A scoped guard that scopes to nothing passes everything."""
    recs = analysis.build_all(built_at="X")
    found = list(_prose_strings(recs))
    assert len(found) > 500, f"only {len(found)} prose strings reached the guard"
