"""The brief's hardest constraint, enforced rather than promised.

"Do not restructure or break any existing pages" and "never modify existing routes
beyond adding links to the new tabs" are easy to honour on day one and easy to
erode by accident on day three, when a one-line fix to price_screen.py would save
an hour. These tests make that erosion loud.

They diff the branch against its merge base with the default branch, so they keep
working as the branch grows and they do not care what order the commits landed in.

Fourth session, 2026-09-07: Joseph asked for a complete visual redesign, which
collides with the freeze on ``dashboard/index.html``. The freeze is lifted for
``dashboard/`` only. ``dashboard/data.js`` stays frozen because the generator
that writes it, ``scripts/build_dashboard.py``, is still frozen, and a hand edit
to a generated file would be overwritten by the next pipeline run. Everything
outside ``dashboard/`` is as untouchable as it was. NOTES.md section 9a.
"""
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent

# Everything that existed before this work started and must come through unchanged.
UNTOUCHABLE = [
    "scripts/serve.py",
    "scripts/config.py",
    "scripts/universe.py",
    "scripts/fundamentals.py",
    "scripts/quality_screen.py",
    "scripts/price_screen.py",
    "scripts/build_dashboard.py",
    "scripts/write_research.py",
    "scripts/research_notes.py",
    "scripts/email_picks.py",
    "scripts/email_hero_gif.py",
    "scripts/_repull.py",
    "README.md",
    "criteria.md",
    "journal.md",
    "requirements.txt",
    "research/",
    "universe/quality_scores_latest.csv",
    "universe/price_screen_latest.csv",
    "universe/quality_top150.csv",
    "universe/universe_latest.csv",
    "dashboard/data.js",
]


def git(*args):
    r = subprocess.run(["git", *args], capture_output=True, text=True, cwd=str(ROOT))
    return r.stdout.strip(), r.returncode


def base_ref():
    """The commit before the analysis layer existed.

    The first version diffed against the merge base with ``main``. That worked
    while the work lived on a branch and broke the day it merged: from then on
    the merge base was HEAD itself, the diff was empty, and the test that expects
    to see the two nav links failed while the test that expects nothing else to
    have moved started counting every generated page as a pre-existing file.

    "Pre-existing" means before this work started, and the work started with
    PLAN.md one commit before ``scripts/an/``, so the base is the parent of the
    earliest commit that added either. The merge base is kept as a fallback for
    a shallow clone that cannot see that far back.
    """
    out, code = git("log", "--diff-filter=A", "--format=%H", "--", "PLAN.md", "scripts/an/__init__.py")
    if code == 0 and out:
        first = out.splitlines()[-1]
        parent, code = git("rev-parse", "--verify", "--quiet", f"{first}^")
        if code == 0 and parent:
            return parent
    for ref in ("origin/main", "main", "origin/master", "master"):
        out, code = git("merge-base", "HEAD", ref)
        if code == 0 and out:
            return out
    return None


@pytest.fixture(scope="module")
def base():
    b = base_ref()
    if not b:
        pytest.skip("no main branch to diff against")
    return b


def test_the_original_pipeline_is_untouched(base):
    out, _ = git("diff", "--stat", base, "--", *UNTOUCHABLE)
    assert not out, f"files that had to stay unchanged were modified:\n{out}"


def test_index_html_still_links_to_the_new_pages(base):
    """The front page may be rewritten now (section 9a). Whatever it becomes, it
    has to keep the two links the earlier sessions were allowed to add."""
    src = (ROOT / "dashboard" / "index.html").read_text(encoding="utf-8")
    assert 'href="analyze/"' in src
    assert 'href="positioning/"' in src


def test_everything_else_new_is_additive(base):
    """Any other pre-existing file that changed is a bug in this work, not a feature.

    ``dashboard/`` is the one directory where a pre-existing file may change,
    apart from ``data.js``, which is generated by a frozen script.
    """
    out, _ = git("diff", "--name-status", base)
    modified = [ln.split("\t", 1)[1] for ln in out.splitlines() if ln.startswith("M")]
    allowed = {".gitignore", "setup.ps1"}
    unexpected = [m for m in modified
                  if m not in allowed and not (m.startswith("dashboard/") and m != "dashboard/data.js")]
    assert not unexpected, f"pre-existing files modified: {unexpected}"


def test_gitignore_only_gained_lines(base):
    diff, _ = git("diff", base, "--unified=0", "--", ".gitignore")
    if not diff:
        return
    removed = [ln for ln in diff.splitlines() if ln.startswith("-") and not ln.startswith("---")]
    assert not removed, f".gitignore lost lines:\n{diff}"


def test_portfolio_is_still_ignored_and_still_absent(base):
    _, code = git("check-ignore", "-q", "portfolio/holdings.csv")
    assert code == 0
    out, _ = git("ls-files", "portfolio")
    assert not out, "a personal position file is tracked"


def test_the_front_page_journal_still_disagrees_with_the_new_pages():
    """A known divergence, pinned here so it is not mistaken for a fresh bug.

    ``build_dashboard.py`` parses journal headings with ``(\\S+)`` for the ticker,
    so a heading naming five names produces one entry under the first and folds
    the other four into the title. The new pages parse the same file correctly
    and show sixteen names where the front page shows thirteen.

    Both the generator and its output are on the untouchable list, and the brief
    says not to modify existing routes beyond adding links, so this is documented
    rather than fixed. If someone lifts that constraint later, the repair is one
    line: give ``build_dashboard.py`` the grammar in ``scripts/an/journal.py``.
    This test fails the day that happens, which is the point.
    """
    import json
    import re

    from an import journal

    src = (ROOT / "dashboard" / "data.js").read_text(encoding="utf-8")
    front = json.loads(src[src.index("{"):].rstrip().rstrip(";"))["journal"]
    front_tickers = {e["ticker"] for e in front if e["ticker"] != "SYSTEM"}
    ours = set(journal.by_ticker())

    assert front_tickers < ours, "the front page caught up; delete this test and the note in NOTES.md"
    assert ours - front_tickers == {"NOW", "ACN", "AMAT", "NVR"}
    assert any(re.match(r"^[A-Z]+ [A-Z]+", e["title"]) for e in front), \
        "expected the folded multi-ticker title on the front page"


def test_the_generator_of_that_divergence_is_the_untouchable_one():
    """The reason it cannot be fixed here, asserted rather than asserted-in-a-comment."""
    assert "scripts/build_dashboard.py" in UNTOUCHABLE
    assert "dashboard/data.js" in UNTOUCHABLE
    src = (ROOT / "scripts" / "build_dashboard.py").read_text(encoding="utf-8")
    assert r"(\S+)\s*(.*?)$" in src, "build_dashboard.py's journal grammar changed; recheck this note"
